// ================================================================
//
//                    S  W  A  O
//
//  Sovereign Workload Assessment and Onboarding
//  CLI orchestrator
//
//  Free and Open-Source Software (FOSS)
//
//  Website       :  https://steady-echo-yp4z.here.now/
//  Technical Docs:  https://accenture.github.io/SWAO/en/
//  Source Code   :  https://github.com/Accenture/SWAO
//
// ================================================================

// Post-run report-output scrubber (#0354 follow-up, sprint-038).
//
// Sweeps `wsp/runs/<ts>/` after an assess run completes and scrubs
// every text file in place using the same redactor classes as the
// pre-LLM wrap. See design 032 §13.
//
// Rationale for the sweep approach (vs per-call-site scrubbing):
//
//   - ~10 writeFileSync sites across assess.ts + exports/star.ts +
//     commands/derive-plan.ts + commands/challenge.ts + others;
//     per-site wrapping is invasive and easy to drift.
//   - The directory boundary is a single fail-closed hook: any new
//     pass / exporter that writes into wsp/runs/<ts>/ inherits
//     scrubbing automatically.
//   - Inputs (wsp/inputs/, .swao.yml, source/) are NEVER touched --
//     they live outside wsp/runs/ and the operator needs raw inputs
//     to debug. Only the OUTPUT directory is swept.
//   - The redaction-report.json itself is skipped so the audit trail
//     records the scrub event without scrubbing its own counts.
//
// Recovery: if the sweep crashes partway, re-run `swao assess` to
// regenerate the run dir. The raw inputs are unaffected.

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, extname } from 'node:path';
import { redactForReport } from './redact-pre-llm.js';
import { recordRedaction } from '@swao/core';

// File extensions that contain scrubbable text. Binary outputs
// (.xlsx, .pdf, .png, .jpg, .zip, .tar.gz, .sig, .pem, .crt) are
// skipped; they require format-aware scrubbing that is out of scope
// for sprint-038. PDF text content is generated by the LLM and
// scrubbed at the egress wrap; embedded raw-evidence excerpts are a
// sprint-039 follow-up (design 032 §13 noted).
const SCRUBBABLE_EXTENSIONS = new Set([
  '.json', '.yaml', '.yml', '.csv', '.tsv', '.md', '.txt', '.html', '.xml', '.log',
]);

// File basenames the sweep MUST NOT touch:
//   - redaction-report.json    -- the sweep's own audit trail
//   - latest.txt               -- the pointer file (`runs/<ts>`); plain text + no PII surface
//   - signatures, hashes       -- modifying these breaks integrity
//   - .gitignore               -- not a report artefact
//   - wsp.yaml                 -- #0824: engagement metadata (partnership_lead,
//                                  client_code, etc.) is entered voluntarily by
//                                  the user during `swao init`. wsp.yaml is written
//                                  AFTER all LLM passes complete and is never sent
//                                  to the LLM; scrubbing it silently erases info the
//                                  user chose to provide.
const SKIP_BASENAMES = new Set([
  'redaction-report.json',
  'latest.txt',
  '.gitignore',
  'manifest.sig',
  'manifest.sha256',
  'wsp.yaml',
]);

function shouldScrub(filePath: string): boolean {
  const base = filePath.split(/[/\\]/).pop() ?? '';
  if (SKIP_BASENAMES.has(base)) return false;
  if (base.endsWith('.sig') || base.endsWith('.sha256') || base.endsWith('.asc')) return false;
  const ext = extname(filePath).toLowerCase();
  return SCRUBBABLE_EXTENSIONS.has(ext);
}

function walkFiles(dir: string, out: string[]): void {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      walkFiles(full, out);
    } else if (st.isFile()) {
      out.push(full);
    }
  }
}

export interface ScrubRunDirectoryResult {
  files_scanned: number;
  files_scrubbed: number;
  total_chars_removed: number;
}

/**
 * Walk the run directory, scrub every text file in place, and append
 * one report_write entry per file with non-zero counts to the
 * redaction-report sink. Files with zero matches are not recorded
 * (keeps the audit trail focused on real events).
 */
export function scrubRunDirectory(runDir: string): ScrubRunDirectoryResult {
  const files: string[] = [];
  walkFiles(runDir, files);

  let files_scrubbed = 0;
  let total_chars_removed = 0;

  for (const filePath of files) {
    if (!shouldScrub(filePath)) continue;

    let original: string;
    try {
      original = readFileSync(filePath, 'utf-8');
    } catch {
      // Unreadable (e.g. permission-denied) -- skip; do not crash the
      // sweep. The pre-flight doctor should catch this earlier.
      continue;
    }

    const { text: scrubbed, counts } = redactForReport(original);

    if (scrubbed !== original) {
      writeFileSync(filePath, scrubbed, 'utf-8');
      files_scrubbed += 1;
      const removed = original.length - scrubbed.length;
      total_chars_removed += removed;
      recordRedaction({
        surface: 'report_write',
        provider: 'report-scrub',
        model: relative(runDir, filePath).replace(/\\/g, '/'),
        input_chars: original.length,
        scrubbed_chars: scrubbed.length,
        counts,
      });
    }
  }

  return {
    files_scanned: files.length,
    files_scrubbed,
    total_chars_removed,
  };
}
