// ================================================================
//
//                    S  W  A  O
//
//  Sovereign Workload Assessment and Onboarding
//  CLI orchestrator
//
//  Free and Open-Source Software (FOSS)
//
//  Website       :  https://steady-echo-yp4z.here.now/
//  Technical Docs:  https://accenture.github.io/SWAO/en/
//  Source Code   :  https://github.com/Accenture/SWAO
//
// ================================================================

/**
 * Shared helper for SWAO E2E journey tests.
 *
 * Resolves the correct binary for the current platform and provides a `run()`
 * helper that spawns it with piped stdio.
 */
import { spawnSync, SpawnSyncReturns, spawn, ChildProcess } from 'child_process';
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'fs';
import { join, resolve, dirname } from 'path';
import { tmpdir } from 'os';
import { fileURLToPath } from 'url';
import { readdir } from 'fs/promises';
import type { Page, TestInfo } from '@playwright/test';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '../../../../');

export const DIST_BIN = join(REPO_ROOT, 'dist-bin');
export const WORKSPACE = join(REPO_ROOT, 'examples', 'portfolio-workspace', 'portfolio');

function binaryPath(): string {
  if (process.platform === 'win32') return join(DIST_BIN, 'swao-enterprise-win.exe');
  if (process.platform === 'darwin') return join(DIST_BIN, 'swao-macos');
  return join(DIST_BIN, 'swao-linux');
}

export const BIN = binaryPath();
export const hasBinary = existsSync(BIN);

export interface RunResult {
  stdout: string;
  stderr: string;
  combined: string;
  status: number;
}

export function run(
  args: string[],
  options: { cwd?: string; env?: Record<string, string | undefined> } = {},
): RunResult {
  const result: SpawnSyncReturns<string> = spawnSync(BIN, args, {
    cwd: options.cwd ?? WORKSPACE,
    encoding: 'utf-8',
    timeout: 30_000,
    env: { ...process.env, ...options.env },
  });
  const stdout = result.stdout ?? '';
  const stderr = result.stderr ?? '';
  return { stdout, stderr, combined: stdout + stderr, status: result.status ?? -1 };
}

/**
 * Attach CLI stdout/stderr to the Playwright HTML report so the output is
 * visible per-test in playwright-report/index.html.
 */
export function attachOutput(testInfo: TestInfo, label: string, result: RunResult): void {
  const body = [
    `$ swao ${label}`,
    `exit: ${result.status}`,
    result.stdout ? `--- stdout ---\n${result.stdout}` : '',
    result.stderr ? `--- stderr ---\n${result.stderr}` : '',
  ].filter(Boolean).join('\n');
  void testInfo.attach(`${label}`, { body, contentType: 'text/plain' });
}

/**
 * Creates an isolated temp workspace for setup journey tests.
 * Caller is responsible for cleanup (use afterEach/afterAll).
 */
export function makeTempWorkspace(appId: string): string {
  const dir = join(tmpdir(), `swao-e2e-${Date.now()}`);
  mkdirSync(dir, { recursive: true });
  const appsDir = join(dir, 'apps', appId);
  mkdirSync(appsDir, { recursive: true });
  const yaml =
    `# .swao.yml -- generated by E2E test\n` +
    `wsp_version: "0.9"\n` +
    `app_id: ${appId}\n` +
    `assessment_date: ~\n` +
    `assessor: ~\n` +
    `imports_dir: imports/\n`;
  writeFileSync(join(dir, '.swao.yml'), yaml, 'utf-8');
  return dir;
}

/**
 * Resolve the path to the latest HTML publication for the given app (#0877).
 * Checks wsp/publications/ first (renderModeA output written by report --format html),
 * then falls back to the legacy apps/<id>/publication.html path.
 * Returns null if no publication exists yet.
 */
export function resolveLatestPublication(appId: string): string | null {
  // renderModeA writes to apps/<id>/wsp/publications/<runTs>-<appId>.html
  const pubDir = join(WORKSPACE, 'apps', appId, 'wsp', 'publications');
  if (existsSync(pubDir)) {
    const files = readdirSync(pubDir)
      .filter(f => f.endsWith('.html') && !f.startsWith('latest-'))
      .sort((a, b) => b.localeCompare(a)); // descending by filename (timestamp-prefixed)
    if (files.length > 0) return join(pubDir, files[0]!);
  }
  // Legacy path: apps/<id>/publication.html
  const legacyPath = join(WORKSPACE, 'apps', appId, 'publication.html');
  if (existsSync(legacyPath)) return legacyPath;
  return null;
}

/**
 * Navigate Playwright to a generated HTML publication for the given appId.
 * Checks wsp/publications/ (renderModeA output from report --format html) first,
 * then falls back to the legacy apps/<id>/publication.html path.
 * Throws if no publication file is found.
 */
export async function loadReport(page: Page, appId: string): Promise<void> {
  const reportPath = resolveLatestPublication(appId);
  if (!reportPath) {
    throw new Error(
      `No HTML publication found for ${appId}. ` +
      `Run: swao report --app ${appId} --format html`,
    );
  }
  await page.goto(`file://${reportPath}`);
  await page.waitForLoadState('networkidle');
}

/**
 * Start the HTML Editor server for J7 specs.
 * Returns { url, close } where close() terminates the server process.
 */
export async function startEditorServer(
  appId: string,
  port: number = 4001,
): Promise<{ url: string; close: () => Promise<void> }> {
  const proc: ChildProcess = spawn(
    BIN,
    ['publish', '--edit', '--app', appId, '--port', String(port)],
    { cwd: WORKSPACE, stdio: 'pipe' },
  );
  await new Promise<void>((resolve, reject) => {
    const timeout = setTimeout(() => reject(new Error('Editor server timeout')), 15000);
    proc.stdout?.on('data', (chunk: Buffer) => {
      if (chunk.toString().includes('localhost:' + port)) {
        clearTimeout(timeout);
        resolve();
      }
    });
    proc.on('error', reject);
  });
  return {
    url: `http://localhost:${port}`,
    close: () => new Promise<void>((res) => { proc.kill(); proc.on('close', () => res()); }),
  };
}

/**
 * Assert all 17 standard star-schema CSV files are present in starDir.
 * Throws if any expected file is missing.
 */
export async function validateStarSchema(starDir: string): Promise<void> {
  const EXPECTED = [
    'dim_app.csv', 'dim_control.csv', 'dim_evidence.csv', 'dim_pass.csv',
    'dim_regime.csv', 'dim_severity.csv', 'dim_wave.csv',
    'fact_assessments.csv', 'fact_controls.csv', 'fact_findings.csv',
    'fact_pass_runs.csv', 'fact_risks.csv', 'fact_runs.csv', 'fact_signals.csv',
    'link_control_evidence.csv', 'link_control_signal.csv', 'link_signal_evidence.csv',
  ];
  const files = await readdir(starDir);
  for (const expected of EXPECTED) {
    if (!files.includes(expected)) throw new Error(`Missing star CSV: ${expected} in ${starDir}`);
  }
}

/**
 * Stub for MCP tool invocation -- to be extended by #0140.
 */
export async function runMcpTool(
  _toolName: string,
  _params: Record<string, unknown>,
): Promise<unknown> {
  throw new Error('runMcpTool not yet implemented -- see issue #0140');
}
